openapi: 3.1.0
x-stoplight:
  id: 83330f7496caa
info:
  title: Senzory
  version: '2.0'
  summary: 'API pro obsluhu senzorů, naměřených hodnot a upozornění...'
  contact:
    name: Miroslav Holec
    url: 'https://www.miroslavholec.cz'
    email: mirek@miroslavholec.cz
  license:
    name: Demo
    url: 'https://www.restapi.cz'
  description: Ukázkové API pro účely školení REST API
servers:
  - url: 'http://127.0.0.1:4010'
    description: Local Prism Mock
tags:
  - name: Metriky
    description: Správa upozornění vázaných na senzory
    x-tag-expanded: false
  - name: Senzory
    description: Správa senzorů
    x-tag-expanded: false
  - name: Upozornění
    description: Správa upozornění vázaných na senzory
    x-tag-expanded: false
paths:
  /sensors:
    get:
      summary: Seznam senzorů s filtrováním
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sensors'
              examples:
                DashboardList:
                  value:
                    items:
                      - sensorId: S1-HALA-A-PRG
                        name: S1-HALA-A-PRG
                        unit: °C
                        type: S1
                      - sensorId: S2-HALA-A-PRG
                        name: S2-HALA-A-PRG
                        unit: '%'
                        type: S2
                      - sensorId: S1-HALA-B-PRG
                        name: S1-HALA-B-PRG
                        unit: °C
                        type: S1
                      - sensorId: S2-HALA-B-PRG
                        name: S2-HALA-B-PRG
                        unit: '%'
                        type: S2
                      - sensorId: S3-HALA-B-PRG
                        name: S3-HALA-B-PRG
                        unit: m/s
                        type: S3
                    totalItems: 5
        '400':
          $ref: '#/components/responses/400-BadRequest'
        '500':
          $ref: '#/components/responses/500-InternalError'
      operationId: GetSensors
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pagesize'
      description: 'Seznam senzorů s přehledem průměrně naměřených hodnot za zvolený časový úsek. Z průměru jsou vyloučeny hodnoty, které systém neshledal validními.'
      tags:
        - Senzory
      x-stoplight:
        id: o1t67s2kpzwhe
  '/sensors/{id}':
    parameters:
      - schema:
          type: string
          example: S1-HALA-A-PRG
        name: id
        in: path
        required: true
        description: Identifikátor senzoru
    get:
      summary: Detaily senzoru
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sensor'
              examples:
                Detail:
                  value:
                    sensorId: S1-HALA-A-PRG
                    name: S1-HALA-A-PRG
                    unit: °C
                    type: S1
        '404':
          $ref: '#/components/responses/404-NotFound'
        '500':
          $ref: '#/components/responses/500-InternalError'
      operationId: GetSensorById
      description: Detailní informace o senzory. Nezahrnuje podrobnosti ohledně naměřených hodnot.
      tags:
        - Senzory
      x-stoplight:
        id: x5xpug38gd735
  /measurings:
    parameters: []
    get:
      summary: Hodnoty pro senzory
      operationId: GetMeasurings
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Measurings'
              examples:
                Paging:
                  value:
                    items:
                      - valueId: 1
                        sensorid: S1-HALA-A-PRG
                        obtained: '2024-04-01T13:00:00'
                        value: 24.4
                        status: valid
                      - valueId: 2
                        sensorid: S1-HALA-A-PRG
                        obtained: '2024-04-01T13:05:00'
                        value: 24.5
                        status: valid
                      - valueId: 3
                        sensorid: S1-HALA-A-PRG
                        obtained: '2024-04-01T13:10:00'
                        value: 91.5
                        status: invalid
                      - valueId: 4
                        sensorid: S1-HALA-A-PRG
                        obtained: '2024-04-01T13:15:00'
                        value: 24.6
                        status: valid
                      - valueId: 5
                        sensorid: S1-HALA-A-PRG
                        obtained: '2024-04-01T13:20:00'
                        value: 24.7
                        status: valid
                    totalItems: 2339
        '400':
          $ref: '#/components/responses/400-BadRequest'
        '500':
          $ref: '#/components/responses/500-InternalError'
      parameters:
        - schema:
            type: string
            format: date-time
            example: '2024-04-17T17:19:47'
          in: query
          name: dateFrom
          description: Datum od kdy se zvažují hodnoty
        - schema:
            type: string
            format: date-time
            example: '2024-05-27T17:19:47'
          in: query
          name: dateTo
          description: Datum do kdy se zvažují hodnoty
        - schema:
            type: string
            example: 'S1-HALA-A-PRG, S2-HALA-A-PRG'
          in: query
          name: sensorIds
          description: ID senzorů
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pagesize'
      description: Hodnoty naměřené na vybraných senzorech
      tags:
        - Senzory
      x-stoplight:
        id: 6gp86a8hiyn4n
  '/measurings/{id}':
    parameters:
      - schema:
          type: integer
          format: int64
          example: 52656333
        name: id
        in: path
        required: true
        description: ID naměřené hodnoty
    delete:
      summary: Odstranění naměřené hodnoty
      operationId: DeleteMeasuring
      responses:
        '204':
          description: No Content
        '404':
          $ref: '#/components/responses/404-NotFound'
        '500':
          $ref: '#/components/responses/500-InternalError'
      description: Odstranění jedné naměřené hodnoty k senzoru
      tags:
        - Senzory
      x-stoplight:
        id: 9xb9hq6xsru8l
  '/alerts/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Identifikátor alertu shodný s identifikátorem senzoru
    get:
      summary: Zobrazení alertu nad senzorem
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alert'
              examples:
                Default:
                  value:
                    sensorId: S1-HALA-A-PRG
                    valueFrom: 13
                    valueTo: 20
                    threshold: PT20M
                    email: info@xyz.cz
                    state: 'off'
        '404':
          $ref: '#/components/responses/404-NotFound'
        '500':
          $ref: '#/components/responses/500-InternalError'
      operationId: GetSensorAlert
      description: Informace k alertu nad senzorem. Alert a senzor spolu sdílí jedno ID.
      tags:
        - Upozornění
      x-stoplight:
        id: d6uzgw9g7ssjc
    put:
      summary: Úprava alertu v nastavení senzoru
      operationId: UpdateSensorAlert
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alert'
              examples:
                EnableAlert:
                  value:
                    sensorId: S1-HALA-A-PRG
                    valueFrom: 13
                    valueTo: 20
                    threshold: PT20M
                    email: info@xyz.cz
                    state: 'on'
        '400':
          $ref: '#/components/responses/400-BadRequest'
        '404':
          $ref: '#/components/responses/404-NotFound'
        '500':
          $ref: '#/components/responses/500-InternalError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AlertUpdate'
            examples:
              Example 1:
                value:
                  valueFrom: 13
                  valueTo: 20
                  threshold: PT20M
                  email: info@xyz.cz
                  state: 'on'
      description: Aktualizace nastavení alertu.
      tags:
        - Upozornění
      x-stoplight:
        id: cahzb3lf25ycc
  /metrics:
    get:
      summary: Statistiky pro senzory
      tags:
        - Metriky
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Metrics'
              examples:
                Dashboard:
                  value:
                    items:
                      - sensorId: S1-HALA-A-PRG
                        dateFrom: '2024-01-01T12:00:00'
                        dateTo: '2024-01-02T12:05:00'
                        value: 24.4
                      - sensorId: S2-HALA-A-PRG
                        dateFrom: '2024-01-01T12:00:00'
                        dateTo: '2024-01-02T12:05:00'
                        value: 0.68
                      - sensorId: S1-HALA-B-PRG
                        dateFrom: '2024-01-01T12:00:00'
                        dateTo: '2024-01-02T12:05:00'
                        value: 23.1
                      - sensorId: S2-HALA-B-PRG
                        dateFrom: '2024-01-01T12:00:00'
                        dateTo: '2024-01-02T12:05:00'
                        value: 0.66
                      - sensorId: S3-HALA-B-PRG
                        dateFrom: '2024-01-01T12:00:00'
                        dateTo: '2024-01-02T12:05:00'
                        value: 1
                SensorGraphDetail:
                  value:
                    items:
                      - sensorId: S1-HALA-A-PRG
                        dateFrom: '2024-04-01T00:00:00'
                        dateTo: '2024-04-01T23:59:59'
                        value: 1.1
                      - sensorId: S1-HALA-A-PRG
                        dateFrom: '2024-04-02T00:00:00'
                        dateTo: '2024-04-02T23:59:59'
                        value: 5
                      - sensorId: S1-HALA-A-PRG
                        dateFrom: '2024-04-03T00:00:00'
                        dateTo: '2024-04-03T23:59:59'
                        value: 10
                      - sensorId: S1-HALA-A-PRG
                        dateFrom: '2024-04-04T00:00:00'
                        dateTo: '2024-04-04T23:59:59'
                        value: 11.2
                      - sensorId: S1-HALA-A-PRG
                        dateFrom: '2024-04-05T00:00:00'
                        dateTo: '2024-04-05T23:59:59'
                        value: 13.4
                      - sensorId: S1-HALA-A-PRG
                        dateFrom: '2024-04-06T00:00:00'
                        dateTo: '2024-04-06T23:59:59'
                        value: 16.2
                      - sensorId: S1-HALA-A-PRG
                        dateFrom: '2024-04-07T00:00:00'
                        dateTo: '2024-04-07T23:59:59'
                        value: 19.9
                      - sensorId: S1-HALA-A-PRG
                        dateFrom: '2024-04-08T00:00:00'
                        dateTo: '2024-04-08T23:59:59'
                        value: 22.3
                      - sensorId: S1-HALA-A-PRG
                        dateFrom: '2024-04-09T00:00:00'
                        dateTo: '2024-04-09T23:59:59'
                        value: 19.8
        '400':
          $ref: '#/components/responses/400-BadRequest'
        '500':
          $ref: '#/components/responses/500-InternalError'
      operationId: GetMetrics
      x-stoplight:
        id: 3ufa4ffokxy60
      description: Zobrazení statistik k vybraným senzorům. Poskládá naměřené hodnoty ve zvoleném časovém intervalu do agregací a aktivuje nad hodnotami vybranou funkci.
      parameters:
        - schema:
            type: string
            example: 'S1-HALA-A-PRG, S2-HALA-A-PRG'
          in: query
          name: sensorids
          description: Čárkou oddělené ID senzorů
          required: true
        - schema:
            type: string
            example: '2024-04-17T17:19:47'
          in: query
          name: datefrom
          description: Datum od kdy se zvažují naměřené hodnoty
        - schema:
            type: string
            example: '2024-05-17T17:19:47'
          in: query
          name: dateto
          description: Datum do kdy se zvažují naměřené hodnoty
        - schema:
            type: string
            enum:
              - avg
              - sum
              - count
              - min
              - max
            default: avg
            example: avg
          in: query
          name: aggregate
          description: Agregační funkce nad hodnotami
        - schema:
            type: string
            default: value
            enum:
              - value
              - hour
              - day
              - week
            example: hour
          in: query
          name: scale
          description: Granularita
components:
  schemas:
    ValidationProblemDetails:
      title: ValidationProblemDetails
      type: object
      description: Chybová struktura dle RFC 9457 rozšířená o kolekci validačních chyb
      x-stoplight:
        id: pw03zh4o2w3kf
      required:
        - title
      properties:
        type:
          type: string
          example: 'https://datatracker.ietf.org/doc/html/rfc9457'
          description: Druh chyby dle RFC (URL)
        title:
          type: string
          example: Validation Failed
          description: Základní chybové sdělení
        status:
          type: integer
          example: 404
          description: Duplicitní status kód dle HTTP
        detail:
          type: string
          example: See errors for more details
          description: Detailní informace k vzniklé chybě
        errors:
          type: array
          description: Pole validačních chyb
          items:
            $ref: '#/components/schemas/ValidationError'
            x-stoplight:
              id: li6dwnx74xjzx
    ProblemDetails:
      title: ProblemDetails
      type: object
      description: Chybová struktura dle RFC 9457
      x-stoplight:
        id: afm8y0z7q5kah
      required:
        - title
      properties:
        type:
          type: string
          example: 'https://datatracker.ietf.org/doc/html/rfc9457'
          description: Typ chyby dle RFC (URL)
        title:
          type: string
          example: Internal Server Error
          description: Základní popis chyby
        status:
          type: integer
          example: 500
          description: Duplicitní HTTP status code
        detail:
          type: string
          example: Available on dev env only
          description: Detailní informace k chybě
    Sensors:
      title: Sensors
      type: object
      description: Struktura popisující seznam senzorů a jejich průměrně naměřené hodnoty za časový interval
      x-stoplight:
        id: sjxgwb1sbdza4
      required:
        - items
        - totalItems
      properties:
        items:
          type: array
          description: Seznam senzorů
          items:
            $ref: '#/components/schemas/Sensor'
            x-stoplight:
              id: z293u7a96xh6v
        totalItems:
          type: integer
          format: int32
          default: 10
          example: 50
          description: Celkový počet položek dle filtru
          x-stoplight:
            id: lwffbxt7gdlw1
    Sensor:
      title: Sensor
      type: object
      description: Detailní informace o senzoru. Senzory jsou nyní v provozu v 5 variantách. Jejich označení je uvedeno vlastností type.
      x-stoplight:
        id: az0mnp73kk779
      required:
        - sensorId
        - name
        - unit
        - type
      properties:
        sensorId:
          type: string
          example: S1-HALA-A-PRG
          description: Unikátní identifikátor senzoru. První dva znaky odlišují typ senzoru.
        name:
          type: string
          example: S1-HALA-A-PRG
          description: Název senzoru
        unit:
          type: string
          example: '%'
          description: 'Jednotka, ve které je snímána hodnota'
        type:
          type: string
          example: S1
          description: Typ senzoru
          enum:
            - S1
            - S2
            - S3
            - S4
            - S5
    Measurings:
      title: Measurings
      type: object
      description: 'Datová sada s naměřenými hodnotami pro zvolené senzory  '
      x-stoplight:
        id: q15lew0i711rd
      required:
        - items
        - totalItems
      properties:
        items:
          type: array
          description: Pole s naměřenými hodnotami
          items:
            $ref: '#/components/schemas/Measuring'
            x-stoplight:
              id: qi0byhcc3wsqm
        totalItems:
          type: integer
          format: int32
          minimum: 0
          example: 2339
          description: Celkový počet naměřených hodnot
          x-stoplight:
            id: b9ycfns5kgr88
    Measuring:
      title: Measuring
      type: object
      description: Hodnota naměřené na určitém senzoru
      x-stoplight:
        id: junuiv3k56oup
      required:
        - valueId
        - sensorid
        - obtained
        - value
        - status
      properties:
        valueId:
          type: integer
          format: int64
          example: 1
          description: Unikátní identifikátor naměřené hodnoty v systému
          minimum: 1
        sensorid:
          type: string
          x-stoplight:
            id: l8nft5v3s7igo
          example: S1-HALA-A-PRG
          description: 'Identifikátor senzoru, ke kterému se naměřená hodnota váže'
        obtained:
          type: string
          format: date-time
          description: Datum a čas naměření hodnoty
          x-stoplight:
            id: 2wz9ipkcliugz
          example: '2024-01-01T12:00:00'
        value:
          type: number
          format: double
          example: 0.98
          description: Naměřená hodnota
        status:
          type: string
          description: Stav naměřené hodnoty. Určuje například platnost.
          enum:
            - valid
            - invalid
          example: valid
    Alert:
      title: Alert
      type: object
      description: Upozornění na vybočení měření mimo prahové hodnoty po definovanou dobu. Prahové hodnoty spadají do intervalu.
      x-stoplight:
        id: obbuqj4i9l2ph
      required:
        - sensorId
        - valueFrom
        - valueTo
        - threshold
        - email
        - state
      properties:
        sensorId:
          type: string
          example: S1-HALA-A-PRG
          description: Identifikátor senzoru
        valueFrom:
          type: number
          format: double
          example: 0.01
          description: Krajní hodnota "od"
        valueTo:
          type: number
          format: double
          example: 0.1
          description: Krajní hodnota "do"
        threshold:
          type: string
          example: PT5M
          description: 'Prahová doba, po kterou je hodnota mimo interval jako duration dle RFC 3339.'
        email:
          type: string
          format: email
          description: 'E-mail, na který je zasíláno upozornění'
        state:
          type: string
          enum:
            - 'on'
            - 'off'
          example: 'on'
          description: Stav alertu
          x-stoplight:
            id: bybkdsk2dyway
    AlertUpdate:
      title: AlertUpdate
      type: object
      x-stoplight:
        id: nezelpyunv6wt
      description: Nastavení alertu senzoru
      required:
        - valueFrom
        - valueTo
        - threshold
        - email
        - state
      properties:
        valueFrom:
          type: number
          format: double
          example: 0.01
          description: Dolní prahová hodnota
        valueTo:
          type: number
          format: double
          example: 0.2
          description: Horní prahová hodnota
        threshold:
          type: string
          example: PT1H30S
          description: Doba vybočení mimo práh jako duration dle RFC 3339
          default: PT5M
        email:
          type: string
          format: email
          description: 'E-mail, na který bude zasláno upozornění'
        state:
          type: string
          description: Stav aleru
          enum:
            - 'on'
            - 'off'
          x-stoplight:
            id: yfcy218k5if4n
    ValidationError:
      title: ValidationError
      x-stoplight:
        id: wj0taqpajwu8s
      type: object
      description: Validační chyba v rámci validace HTTP požadavku
      required:
        - field
        - message
      properties:
        field:
          type: string
          x-stoplight:
            id: hyckfrj7xazu2
          example: Firstname
        message:
          type: string
          x-stoplight:
            id: svi85fitmovtj
          example: Field is required
    Metrics:
      title: Stats
      x-stoplight:
        id: dhnf9f41mw56q
      type: object
      description: Statistické informace pro vybrané senzory
      required:
        - items
      properties:
        items:
          type: array
          x-stoplight:
            id: 1whoutuqg9z2m
          items:
            $ref: '#/components/schemas/Metric'
            x-stoplight:
              id: lksfcmwhue6ya
    Metric:
      title: Metric
      x-stoplight:
        id: 8atw2ekegegk2
      type: object
      description: Statistická hodnota naměřená pro daný senzor (agregační funkce nad hodnotama pro daný senzor).
      required:
        - sensorId
        - dateFrom
        - dateTo
        - value
      properties:
        sensorId:
          type: string
          x-stoplight:
            id: xthnk68pv89i8
          example: S1-HALA-A-PRG
          description: ID senzoru
        dateFrom:
          type: string
          x-stoplight:
            id: xpxjs0bmg0ut1
          format: date-time
          description: 'Datum, od kterého se zvažují hodnoty'
          example: '2024-01-01T12:00:00'
        dateTo:
          type: string
          x-stoplight:
            id: 1et96zjasppqc
          format: date-time
          description: 'Datum, do kterého se zvažují hodnoty'
          example: '2024-01-02T12:00:00'
        value:
          x-stoplight:
            id: 2c9ldyphcva83
          type: number
          format: double
          default: 0
          example: 0.64
          description: Vypočtená hodnota pro časový rozsah dle zvolené agregační funkce.
  responses:
    400-BadRequest:
      description: Chybová odpověď při validaci vstupů. Nejčastější příčinou je nevalidní JSON struktura nebo nevalidní parametry či chybějící parametry v URL query string.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ValidationProblemDetails'
      headers: {}
    404-NotFound:
      description: 'Chybová struktura 404 v situacích, kdy není požadovaný resource nalezen'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
          examples:
            example-1:
              value:
                type: 'https://datatracker.ietf.org/doc/html/rfc7807'
                title: Object Not Found
                status: 400
    500-InternalError:
      description: Chybová struktura 500
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
          examples:
            example-1:
              value:
                type: 'https://datatracker.ietf.org/doc/html/rfc7807'
                title: Internal Server Error
                status: 500
                detail: Available on dev environment
  parameters:
    page:
      name: page
      in: query
      required: false
      schema:
        type: integer
        format: int32
        example: 1
        minimum: -2
        default: 1
      description: číslo stránky
    pagesize:
      name: pagesize
      in: query
      required: false
      schema:
        type: integer
        default: 10
        format: int32
        example: 10
        minimum: 1
        maximum: 500
      description: Počet záznamů na stránku
